name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run Pytest
      env:
        PYTHONPATH: .
      run: pytest
    - name: Lint code
      run: |
        pip install flake8
        flake8 app --ignore=E501,W503
    - name: Check formatting with Black
      run: |
        pip install black
        black --check .
