name: Daily Retrain Embeddings

on:
  schedule:
    - cron: "0 3 * * *"  # Every day at 11 AM Ph Time
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Rebuild embedding store
        run: python retrain.py

      - name: Commit updated model
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add app/model/embedding_store.joblib
          git commit -m "chore: daily embedding update" || echo "No changes"
          git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
